# see http://about.travis-ci.org/docs/user/languages/php/ for more hints

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

before_install:
  - pip install --user codecov
before_script:
  - git clone https://github.com/eustasy/normal-checks.git

script:
  - ./normal-checks/php.sh
  - php normal-checks/json.php
  - php normal-checks/xml.php

after_success:
  - codecov

notifications:
  email:
    recipients:
      - lewisgoddard@eustasy.org
    on_success: change
    on_failure: always
