# see http://about.travis-ci.org/docs/user/languages/php/ for more hints

language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

services:
  - mysql

before_script:
  - git clone https://github.com/eustasy/normal-checks.git
  - sh -c "mysql -e 'CREATE DATABASE IF NOT EXISTS PuffDB;'"
  - php _tests/test.initialize.php

script:
  - ./normal-checks/php.sh
  - php normal-checks/json.php
  - php normal-checks/xml.php
  - php _tests/runonce/test.runonce.php

notifications:
  email:
    recipients:
      - lewisgoddard@eustasy.org
    on_success: change
    on_failure: always
